package require -exact qsys 15.0
set_module_property NAME avg_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME avg_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_assignment hls.cosim.name {avg}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avg_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_package.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library_package.vhd
add_fileset_file dspba_library.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library.vhd
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file avg_function_wrapper.vhd VHDL PATH ip/avg_function_wrapper.vhd
add_fileset_file avg_function.vhd VHDL PATH ip/avg_function.vhd
add_fileset_file bb_avg_B2_sr_1.vhd VHDL PATH ip/bb_avg_B2_sr_1.vhd
add_fileset_file bb_avg_B3.vhd VHDL PATH ip/bb_avg_B3.vhd
add_fileset_file avg_B3_branch.vhd VHDL PATH ip/avg_B3_branch.vhd
add_fileset_file avg_B3_merge.vhd VHDL PATH ip/avg_B3_merge.vhd
add_fileset_file bb_avg_B3_stall_region.vhd VHDL PATH ip/bb_avg_B3_stall_region.vhd
add_fileset_file avg_B3_merge_reg.vhd VHDL PATH ip/avg_B3_merge_reg.vhd
add_fileset_file i_sfc_c0_for_body3_avg_c0_enter26_avg.vhd VHDL PATH ip/i_sfc_c0_for_body3_avg_c0_enter26_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_for_body3_avg_c0_exit31_avg72.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_body3_avg_c0_exit31_avg72.vhd
add_fileset_file i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Z_avg97_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Z_avg97_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_body3_avg_c0_enter26_avg37.vhd VHDL PATH ip/i_sfc_logic_c0_for_body3_avg_c0_enter26_avg37.vhd
add_fileset_file i_acl_pipeline_keep_going_avg39.vhd VHDL PATH ip/i_acl_pipeline_keep_going_avg39.vhd
add_fileset_file i_acl_pop_i1_exitcond18_pop15_avg64.vhd VHDL PATH ip/i_acl_pop_i1_exitcond18_pop15_avg64.vhd
add_fileset_file i_acl_pop_i1_memdep_phi_pop1020_pop17_avg49.vhd VHDL PATH ip/i_acl_pop_i1_memdep_phi_pop1020_pop17_avg49.vhd
add_fileset_file i_acl_pop_i1_notexit1119_pop16_avg68.vhd VHDL PATH ip/i_acl_pop_i1_notexit1119_pop16_avg68.vhd
add_fileset_file i_acl_pop_i32_i_03_pop917_pop14_avg43.vhd VHDL PATH ip/i_acl_pop_i32_i_03_pop917_pop14_avg43.vhd
add_fileset_file i_acl_pop_i32_j_11_pop13_avg41.vhd VHDL PATH ip/i_acl_pop_i32_j_11_pop13_avg41.vhd
add_fileset_file i_acl_pop_i4_fpgaindvars_iv_pop11_avg51.vhd VHDL PATH ip/i_acl_pop_i4_fpgaindvars_iv_pop11_avg51.vhd
add_fileset_file i_acl_push_i1_exitcond18_push15_avg66.vhd VHDL PATH ip/i_acl_push_i1_exitcond18_push15_avg66.vhd
add_fileset_file i_acl_push_i1_memdep_phi_pop1020_push17_avg54.vhd VHDL PATH ip/i_acl_push_i1_memdep_phi_pop1020_push17_avg54.vhd
add_fileset_file i_acl_push_i1_notexit1119_push16_avg70.vhd VHDL PATH ip/i_acl_push_i1_notexit1119_push16_avg70.vhd
add_fileset_file i_acl_push_i1_notexitcond_avg60.vhd VHDL PATH ip/i_acl_push_i1_notexitcond_avg60.vhd
add_fileset_file i_acl_push_i32_i_03_pop917_push14_avg56.vhd VHDL PATH ip/i_acl_push_i32_i_03_pop917_push14_avg56.vhd
add_fileset_file i_acl_push_i32_j_11_push13_avg58.vhd VHDL PATH ip/i_acl_push_i32_j_11_push13_avg58.vhd
add_fileset_file i_acl_push_i4_fpgaindvars_iv_push11_avg62.vhd VHDL PATH ip/i_acl_push_i4_fpgaindvars_iv_push11_avg62.vhd
add_fileset_file i_ffwd_dst_x56_avg46.vhd VHDL PATH ip/i_ffwd_dst_x56_avg46.vhd
add_fileset_file i_sfc_c1_for_body3_avg_c1_enter_avg.vhd VHDL PATH ip/i_sfc_c1_for_body3_avg_c1_enter_avg.vhd
add_fileset_file i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg81.vhd VHDL PATH ip/i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg81.vhd
add_fileset_file i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg99_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg99_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c1_for_body3_avg_c1_exit_A0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c1_for_body3_avg_c1_exit_A0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c1_for_body3_avg_c1_enter_avg75.vhd VHDL PATH ip/i_sfc_logic_c1_for_body3_avg_c1_enter_avg75.vhd
add_fileset_file i_acl_pop_f_sum_12_pop12_avg77.vhd VHDL PATH ip/i_acl_pop_f_sum_12_pop12_avg77.vhd
add_fileset_file i_acl_push_f_sum_12_push12_avg79.vhd VHDL PATH ip/i_acl_push_f_sum_12_push12_avg79.vhd
add_fileset_file floatComponent_i_sfc_logic_c1_for_body3_A0Zo00rf00d06of5q0u.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c1_for_body3_A0Zo00rf00d06of5q0u.vhd
add_fileset_file i_load_unnamed_avg4_avg73.vhd VHDL PATH ip/i_load_unnamed_avg4_avg73.vhd
add_fileset_file readdata_reg_unnamed_avg4_avg0.vhd VHDL PATH ip/readdata_reg_unnamed_avg4_avg0.vhd
add_fileset_file bb_avg_B3_sr_1.vhd VHDL PATH ip/bb_avg_B3_sr_1.vhd
add_fileset_file bb_avg_B4.vhd VHDL PATH ip/bb_avg_B4.vhd
add_fileset_file avg_B4_merge.vhd VHDL PATH ip/avg_B4_merge.vhd
add_fileset_file avg_B4_branch.vhd VHDL PATH ip/avg_B4_branch.vhd
add_fileset_file bb_avg_B4_stall_region.vhd VHDL PATH ip/bb_avg_B4_stall_region.vhd
add_fileset_file i_sfc_c0_for_end_avg_c0_enter36_avg.vhd VHDL PATH ip/i_sfc_c0_for_end_avg_c0_enter36_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_for_end_avg_c0_exit39_avg84.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_end_avg_c0_exit39_avg84.vhd
add_fileset_file i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zavg101_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zavg101_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_end_avg_c0_enter36_avg82.vhd VHDL PATH ip/i_sfc_logic_c0_for_end_avg_c0_enter36_avg82.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_end_avA0Z03p06o303d0jzj0u.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_end_avA0Z03p06o303d0jzj0u.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_end_avA0Z303d06o00rf01pzc.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_end_avA0Z303d06o00rf01pzc.vhd
add_fileset_file i_acl_push_i1_memdep_phi_push10_avg90.vhd VHDL PATH ip/i_acl_push_i1_memdep_phi_push10_avg90.vhd
add_fileset_file i_acl_push_i1_memdep_phi_push10_avg_reg.vhd VHDL PATH ip/i_acl_push_i1_memdep_phi_push10_avg_reg.vhd
add_fileset_file i_ffwd_dst_y67_avg85.vhd VHDL PATH ip/i_ffwd_dst_y67_avg85.vhd
add_fileset_file i_store_memdep_avg88.vhd VHDL PATH ip/i_store_memdep_avg88.vhd
add_fileset_file bb_avg_B4_sr_0.vhd VHDL PATH ip/bb_avg_B4_sr_0.vhd
add_fileset_file bb_avg_B5_sr_0.vhd VHDL PATH ip/bb_avg_B5_sr_0.vhd
add_fileset_file bb_avg_B0_runOnce.vhd VHDL PATH ip/bb_avg_B0_runOnce.vhd
add_fileset_file avg_B0_runOnce_branch.vhd VHDL PATH ip/avg_B0_runOnce_branch.vhd
add_fileset_file avg_B0_runOnce_merge.vhd VHDL PATH ip/avg_B0_runOnce_merge.vhd
add_fileset_file bb_avg_B0_runOnce_stall_region.vhd VHDL PATH ip/bb_avg_B0_runOnce_stall_region.vhd
add_fileset_file avg_B0_runOnce_merge_reg.vhd VHDL PATH ip/avg_B0_runOnce_merge_reg.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_avg0.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_avg0.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_avg_reg.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_avg_reg.vhd
add_fileset_file i_acl_push_i1_wt_limpush_avg2.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_avg2.vhd
add_fileset_file i_acl_push_i1_wt_limpush_avg_reg.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_avg_reg.vhd
add_fileset_file bb_avg_B1_start.vhd VHDL PATH ip/bb_avg_B1_start.vhd
add_fileset_file avg_B1_start_branch.vhd VHDL PATH ip/avg_B1_start_branch.vhd
add_fileset_file avg_B1_start_merge.vhd VHDL PATH ip/avg_B1_start_merge.vhd
add_fileset_file bb_avg_B1_start_stall_region.vhd VHDL PATH ip/bb_avg_B1_start_stall_region.vhd
add_fileset_file i_iord_bl_do_unnamed_avg1_avg14.vhd VHDL PATH ip/i_iord_bl_do_unnamed_avg1_avg14.vhd
add_fileset_file i_sfc_c0_wt_entry_avg_c0_enter_avg.vhd VHDL PATH ip/i_sfc_c0_wt_entry_avg_c0_enter_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_wt_entry_avg_c0_exit_avg10.vhd VHDL PATH ip/i_acl_sfc_exit_c0_wt_entry_avg_c0_exit_avg10.vhd
add_fileset_file i_sfc_logic_c0_wt_entry_avg_c0_enter_avg4.vhd VHDL PATH ip/i_sfc_logic_c0_wt_entry_avg_c0_enter_avg4.vhd
add_fileset_file i_acl_pipeline_keep_going13_avg6.vhd VHDL PATH ip/i_acl_pipeline_keep_going13_avg6.vhd
add_fileset_file i_acl_push_i1_notexitcond14_avg8.vhd VHDL PATH ip/i_acl_push_i1_notexitcond14_avg8.vhd
add_fileset_file avg_B1_start_merge_reg.vhd VHDL PATH ip/avg_B1_start_merge_reg.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_avg12.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_avg12.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_avg_reg.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_avg_reg.vhd
add_fileset_file i_ffwd_src_unnamed_avg2_avg15.vhd VHDL PATH ip/i_ffwd_src_unnamed_avg2_avg15.vhd
add_fileset_file i_ffwd_src_unnamed_avg3_avg17.vhd VHDL PATH ip/i_ffwd_src_unnamed_avg3_avg17.vhd
add_fileset_file bb_avg_B2.vhd VHDL PATH ip/bb_avg_B2.vhd
add_fileset_file avg_B2_branch.vhd VHDL PATH ip/avg_B2_branch.vhd
add_fileset_file avg_B2_merge.vhd VHDL PATH ip/avg_B2_merge.vhd
add_fileset_file bb_avg_B2_stall_region.vhd VHDL PATH ip/bb_avg_B2_stall_region.vhd
add_fileset_file avg_B2_merge_reg.vhd VHDL PATH ip/avg_B2_merge_reg.vhd
add_fileset_file i_sfc_c0_for_cond1_preheader_avg_c0_enter21_avg.vhd VHDL PATH ip/i_sfc_c0_for_cond1_preheader_avg_c0_enter21_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_c0_exit23_avg34.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_c0_exit23_avg34.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_avg95_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_avg95_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond1_preheader_avA0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond1_preheader_avA0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_cond1_preheader_avg_c0_enter21_avg19.vhd VHDL PATH ip/i_sfc_logic_c0_for_cond1_preheader_avg_c0_enter21_avg19.vhd
add_fileset_file i_acl_pipeline_keep_going9_avg21.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_avg21.vhd
add_fileset_file i_acl_pop_i32_i_03_pop9_avg23.vhd VHDL PATH ip/i_acl_pop_i32_i_03_pop9_avg23.vhd
add_fileset_file i_acl_pop_i6_fpgaindvars_iv4_pop8_avg25.vhd VHDL PATH ip/i_acl_pop_i6_fpgaindvars_iv4_pop8_avg25.vhd
add_fileset_file i_acl_push_i1_notexitcond10_avg30.vhd VHDL PATH ip/i_acl_push_i1_notexitcond10_avg30.vhd
add_fileset_file i_acl_push_i32_i_03_push9_avg28.vhd VHDL PATH ip/i_acl_push_i32_i_03_push9_avg28.vhd
add_fileset_file i_acl_push_i6_fpgaindvars_iv4_push8_avg32.vhd VHDL PATH ip/i_acl_push_i6_fpgaindvars_iv4_push8_avg32.vhd
add_fileset_file i_acl_pop_i1_memdep_phi_pop10_avg35.vhd VHDL PATH ip/i_acl_pop_i1_memdep_phi_pop10_avg35.vhd
add_fileset_file i_acl_pop_i1_memdep_phi_pop10_avg_reg.vhd VHDL PATH ip/i_acl_pop_i1_memdep_phi_pop10_avg_reg.vhd
add_fileset_file bb_avg_B5.vhd VHDL PATH ip/bb_avg_B5.vhd
add_fileset_file avg_B5_branch.vhd VHDL PATH ip/avg_B5_branch.vhd
add_fileset_file avg_B5_merge.vhd VHDL PATH ip/avg_B5_merge.vhd
add_fileset_file bb_avg_B5_stall_region.vhd VHDL PATH ip/bb_avg_B5_stall_region.vhd
add_fileset_file i_acl_push_i1_throttle_push_avg93.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_avg93.vhd
add_fileset_file i_acl_push_i1_throttle_push_avg_reg.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_avg_reg.vhd
add_fileset_file i_iowr_bl_return_unnamed_avg5_avg92.vhd VHDL PATH ip/i_iowr_bl_return_unnamed_avg5_avg92.vhd
add_fileset_file i_acl_pipeline_keep_going13_avg_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going13_avg_sr.vhd
add_fileset_file i_acl_pipeline_keep_going13_avg_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going13_avg_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going9_avg_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_avg_sr.vhd
add_fileset_file i_acl_pipeline_keep_going9_avg_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_avg_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going_avg_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going_avg_sr.vhd
add_fileset_file i_acl_pipeline_keep_going_avg_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going_avg_valid_fifo.vhd
add_fileset_file loop_limiter_avg0.vhd VHDL PATH ip/loop_limiter_avg0.vhd
add_fileset_file loop_limiter_avg1.vhd VHDL PATH ip/loop_limiter_avg1.vhd
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file acl_arb2.v SYSTEM_VERILOG PATH ip/acl_arb2.v
add_fileset_file acl_ic_to_avm.v SYSTEM_VERILOG PATH ip/acl_ic_to_avm.v
add_fileset_file avg_internal.v SYSTEM_VERILOG PATH avg_internal.v

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avg_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_package.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library_package.vhd
add_fileset_file dspba_library.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library.vhd
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file avg_function_wrapper.vhd VHDL PATH ip/avg_function_wrapper.vhd
add_fileset_file avg_function.vhd VHDL PATH ip/avg_function.vhd
add_fileset_file bb_avg_B2_sr_1.vhd VHDL PATH ip/bb_avg_B2_sr_1.vhd
add_fileset_file bb_avg_B3.vhd VHDL PATH ip/bb_avg_B3.vhd
add_fileset_file avg_B3_branch.vhd VHDL PATH ip/avg_B3_branch.vhd
add_fileset_file avg_B3_merge.vhd VHDL PATH ip/avg_B3_merge.vhd
add_fileset_file bb_avg_B3_stall_region.vhd VHDL PATH ip/bb_avg_B3_stall_region.vhd
add_fileset_file avg_B3_merge_reg.vhd VHDL PATH ip/avg_B3_merge_reg.vhd
add_fileset_file i_sfc_c0_for_body3_avg_c0_enter26_avg.vhd VHDL PATH ip/i_sfc_c0_for_body3_avg_c0_enter26_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_for_body3_avg_c0_exit31_avg72.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_body3_avg_c0_exit31_avg72.vhd
add_fileset_file i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Z_avg97_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Z_avg97_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_body3_avg_c0_exit3A0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_body3_avg_c0_enter26_avg37.vhd VHDL PATH ip/i_sfc_logic_c0_for_body3_avg_c0_enter26_avg37.vhd
add_fileset_file i_acl_pipeline_keep_going_avg39.vhd VHDL PATH ip/i_acl_pipeline_keep_going_avg39.vhd
add_fileset_file i_acl_pop_i1_exitcond18_pop15_avg64.vhd VHDL PATH ip/i_acl_pop_i1_exitcond18_pop15_avg64.vhd
add_fileset_file i_acl_pop_i1_memdep_phi_pop1020_pop17_avg49.vhd VHDL PATH ip/i_acl_pop_i1_memdep_phi_pop1020_pop17_avg49.vhd
add_fileset_file i_acl_pop_i1_notexit1119_pop16_avg68.vhd VHDL PATH ip/i_acl_pop_i1_notexit1119_pop16_avg68.vhd
add_fileset_file i_acl_pop_i32_i_03_pop917_pop14_avg43.vhd VHDL PATH ip/i_acl_pop_i32_i_03_pop917_pop14_avg43.vhd
add_fileset_file i_acl_pop_i32_j_11_pop13_avg41.vhd VHDL PATH ip/i_acl_pop_i32_j_11_pop13_avg41.vhd
add_fileset_file i_acl_pop_i4_fpgaindvars_iv_pop11_avg51.vhd VHDL PATH ip/i_acl_pop_i4_fpgaindvars_iv_pop11_avg51.vhd
add_fileset_file i_acl_push_i1_exitcond18_push15_avg66.vhd VHDL PATH ip/i_acl_push_i1_exitcond18_push15_avg66.vhd
add_fileset_file i_acl_push_i1_memdep_phi_pop1020_push17_avg54.vhd VHDL PATH ip/i_acl_push_i1_memdep_phi_pop1020_push17_avg54.vhd
add_fileset_file i_acl_push_i1_notexit1119_push16_avg70.vhd VHDL PATH ip/i_acl_push_i1_notexit1119_push16_avg70.vhd
add_fileset_file i_acl_push_i1_notexitcond_avg60.vhd VHDL PATH ip/i_acl_push_i1_notexitcond_avg60.vhd
add_fileset_file i_acl_push_i32_i_03_pop917_push14_avg56.vhd VHDL PATH ip/i_acl_push_i32_i_03_pop917_push14_avg56.vhd
add_fileset_file i_acl_push_i32_j_11_push13_avg58.vhd VHDL PATH ip/i_acl_push_i32_j_11_push13_avg58.vhd
add_fileset_file i_acl_push_i4_fpgaindvars_iv_push11_avg62.vhd VHDL PATH ip/i_acl_push_i4_fpgaindvars_iv_push11_avg62.vhd
add_fileset_file i_ffwd_dst_x56_avg46.vhd VHDL PATH ip/i_ffwd_dst_x56_avg46.vhd
add_fileset_file i_sfc_c1_for_body3_avg_c1_enter_avg.vhd VHDL PATH ip/i_sfc_c1_for_body3_avg_c1_enter_avg.vhd
add_fileset_file i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg81.vhd VHDL PATH ip/i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg81.vhd
add_fileset_file i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg99_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c1_for_body3_avg_c1_exit_avg99_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c1_for_body3_avg_c1_exit_A0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c1_for_body3_avg_c1_exit_A0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c1_for_body3_avg_c1_enter_avg75.vhd VHDL PATH ip/i_sfc_logic_c1_for_body3_avg_c1_enter_avg75.vhd
add_fileset_file i_acl_pop_f_sum_12_pop12_avg77.vhd VHDL PATH ip/i_acl_pop_f_sum_12_pop12_avg77.vhd
add_fileset_file i_acl_push_f_sum_12_push12_avg79.vhd VHDL PATH ip/i_acl_push_f_sum_12_push12_avg79.vhd
add_fileset_file floatComponent_i_sfc_logic_c1_for_body3_A0Zo00rf00d06of5q0u.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c1_for_body3_A0Zo00rf00d06of5q0u.vhd
add_fileset_file i_load_unnamed_avg4_avg73.vhd VHDL PATH ip/i_load_unnamed_avg4_avg73.vhd
add_fileset_file readdata_reg_unnamed_avg4_avg0.vhd VHDL PATH ip/readdata_reg_unnamed_avg4_avg0.vhd
add_fileset_file bb_avg_B3_sr_1.vhd VHDL PATH ip/bb_avg_B3_sr_1.vhd
add_fileset_file bb_avg_B4.vhd VHDL PATH ip/bb_avg_B4.vhd
add_fileset_file avg_B4_merge.vhd VHDL PATH ip/avg_B4_merge.vhd
add_fileset_file avg_B4_branch.vhd VHDL PATH ip/avg_B4_branch.vhd
add_fileset_file bb_avg_B4_stall_region.vhd VHDL PATH ip/bb_avg_B4_stall_region.vhd
add_fileset_file i_sfc_c0_for_end_avg_c0_enter36_avg.vhd VHDL PATH ip/i_sfc_c0_for_end_avg_c0_enter36_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_for_end_avg_c0_exit39_avg84.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_end_avg_c0_exit39_avg84.vhd
add_fileset_file i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zavg101_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zavg101_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_end_avg_c0_exit39_A0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_end_avg_c0_enter36_avg82.vhd VHDL PATH ip/i_sfc_logic_c0_for_end_avg_c0_enter36_avg82.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_end_avA0Z03p06o303d0jzj0u.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_end_avA0Z03p06o303d0jzj0u.vhd
add_fileset_file floatComponent_i_sfc_logic_c0_for_end_avA0Z303d06o00rf01pzc.vhd VHDL PATH ip/floatComponent_i_sfc_logic_c0_for_end_avA0Z303d06o00rf01pzc.vhd
add_fileset_file i_acl_push_i1_memdep_phi_push10_avg90.vhd VHDL PATH ip/i_acl_push_i1_memdep_phi_push10_avg90.vhd
add_fileset_file i_acl_push_i1_memdep_phi_push10_avg_reg.vhd VHDL PATH ip/i_acl_push_i1_memdep_phi_push10_avg_reg.vhd
add_fileset_file i_ffwd_dst_y67_avg85.vhd VHDL PATH ip/i_ffwd_dst_y67_avg85.vhd
add_fileset_file i_store_memdep_avg88.vhd VHDL PATH ip/i_store_memdep_avg88.vhd
add_fileset_file bb_avg_B4_sr_0.vhd VHDL PATH ip/bb_avg_B4_sr_0.vhd
add_fileset_file bb_avg_B5_sr_0.vhd VHDL PATH ip/bb_avg_B5_sr_0.vhd
add_fileset_file bb_avg_B0_runOnce.vhd VHDL PATH ip/bb_avg_B0_runOnce.vhd
add_fileset_file avg_B0_runOnce_branch.vhd VHDL PATH ip/avg_B0_runOnce_branch.vhd
add_fileset_file avg_B0_runOnce_merge.vhd VHDL PATH ip/avg_B0_runOnce_merge.vhd
add_fileset_file bb_avg_B0_runOnce_stall_region.vhd VHDL PATH ip/bb_avg_B0_runOnce_stall_region.vhd
add_fileset_file avg_B0_runOnce_merge_reg.vhd VHDL PATH ip/avg_B0_runOnce_merge_reg.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_avg0.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_avg0.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_avg_reg.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_avg_reg.vhd
add_fileset_file i_acl_push_i1_wt_limpush_avg2.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_avg2.vhd
add_fileset_file i_acl_push_i1_wt_limpush_avg_reg.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_avg_reg.vhd
add_fileset_file bb_avg_B1_start.vhd VHDL PATH ip/bb_avg_B1_start.vhd
add_fileset_file avg_B1_start_branch.vhd VHDL PATH ip/avg_B1_start_branch.vhd
add_fileset_file avg_B1_start_merge.vhd VHDL PATH ip/avg_B1_start_merge.vhd
add_fileset_file bb_avg_B1_start_stall_region.vhd VHDL PATH ip/bb_avg_B1_start_stall_region.vhd
add_fileset_file i_iord_bl_do_unnamed_avg1_avg14.vhd VHDL PATH ip/i_iord_bl_do_unnamed_avg1_avg14.vhd
add_fileset_file i_sfc_c0_wt_entry_avg_c0_enter_avg.vhd VHDL PATH ip/i_sfc_c0_wt_entry_avg_c0_enter_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_wt_entry_avg_c0_exit_avg10.vhd VHDL PATH ip/i_acl_sfc_exit_c0_wt_entry_avg_c0_exit_avg10.vhd
add_fileset_file i_sfc_logic_c0_wt_entry_avg_c0_enter_avg4.vhd VHDL PATH ip/i_sfc_logic_c0_wt_entry_avg_c0_enter_avg4.vhd
add_fileset_file i_acl_pipeline_keep_going13_avg6.vhd VHDL PATH ip/i_acl_pipeline_keep_going13_avg6.vhd
add_fileset_file i_acl_push_i1_notexitcond14_avg8.vhd VHDL PATH ip/i_acl_push_i1_notexitcond14_avg8.vhd
add_fileset_file avg_B1_start_merge_reg.vhd VHDL PATH ip/avg_B1_start_merge_reg.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_avg12.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_avg12.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_avg_reg.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_avg_reg.vhd
add_fileset_file i_ffwd_src_unnamed_avg2_avg15.vhd VHDL PATH ip/i_ffwd_src_unnamed_avg2_avg15.vhd
add_fileset_file i_ffwd_src_unnamed_avg3_avg17.vhd VHDL PATH ip/i_ffwd_src_unnamed_avg3_avg17.vhd
add_fileset_file bb_avg_B2.vhd VHDL PATH ip/bb_avg_B2.vhd
add_fileset_file avg_B2_branch.vhd VHDL PATH ip/avg_B2_branch.vhd
add_fileset_file avg_B2_merge.vhd VHDL PATH ip/avg_B2_merge.vhd
add_fileset_file bb_avg_B2_stall_region.vhd VHDL PATH ip/bb_avg_B2_stall_region.vhd
add_fileset_file avg_B2_merge_reg.vhd VHDL PATH ip/avg_B2_merge_reg.vhd
add_fileset_file i_sfc_c0_for_cond1_preheader_avg_c0_enter21_avg.vhd VHDL PATH ip/i_sfc_c0_for_cond1_preheader_avg_c0_enter21_avg.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_c0_exit23_avg34.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_c0_exit23_avg34.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_avg95_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond1_preheader_avA0Z_avg95_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_for_cond1_preheader_avA0Zvg_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_for_cond1_preheader_avA0Zvg_full_detector.vhd
add_fileset_file i_sfc_logic_c0_for_cond1_preheader_avg_c0_enter21_avg19.vhd VHDL PATH ip/i_sfc_logic_c0_for_cond1_preheader_avg_c0_enter21_avg19.vhd
add_fileset_file i_acl_pipeline_keep_going9_avg21.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_avg21.vhd
add_fileset_file i_acl_pop_i32_i_03_pop9_avg23.vhd VHDL PATH ip/i_acl_pop_i32_i_03_pop9_avg23.vhd
add_fileset_file i_acl_pop_i6_fpgaindvars_iv4_pop8_avg25.vhd VHDL PATH ip/i_acl_pop_i6_fpgaindvars_iv4_pop8_avg25.vhd
add_fileset_file i_acl_push_i1_notexitcond10_avg30.vhd VHDL PATH ip/i_acl_push_i1_notexitcond10_avg30.vhd
add_fileset_file i_acl_push_i32_i_03_push9_avg28.vhd VHDL PATH ip/i_acl_push_i32_i_03_push9_avg28.vhd
add_fileset_file i_acl_push_i6_fpgaindvars_iv4_push8_avg32.vhd VHDL PATH ip/i_acl_push_i6_fpgaindvars_iv4_push8_avg32.vhd
add_fileset_file i_acl_pop_i1_memdep_phi_pop10_avg35.vhd VHDL PATH ip/i_acl_pop_i1_memdep_phi_pop10_avg35.vhd
add_fileset_file i_acl_pop_i1_memdep_phi_pop10_avg_reg.vhd VHDL PATH ip/i_acl_pop_i1_memdep_phi_pop10_avg_reg.vhd
add_fileset_file bb_avg_B5.vhd VHDL PATH ip/bb_avg_B5.vhd
add_fileset_file avg_B5_branch.vhd VHDL PATH ip/avg_B5_branch.vhd
add_fileset_file avg_B5_merge.vhd VHDL PATH ip/avg_B5_merge.vhd
add_fileset_file bb_avg_B5_stall_region.vhd VHDL PATH ip/bb_avg_B5_stall_region.vhd
add_fileset_file i_acl_push_i1_throttle_push_avg93.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_avg93.vhd
add_fileset_file i_acl_push_i1_throttle_push_avg_reg.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_avg_reg.vhd
add_fileset_file i_iowr_bl_return_unnamed_avg5_avg92.vhd VHDL PATH ip/i_iowr_bl_return_unnamed_avg5_avg92.vhd
add_fileset_file i_acl_pipeline_keep_going13_avg_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going13_avg_sr.vhd
add_fileset_file i_acl_pipeline_keep_going13_avg_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going13_avg_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going9_avg_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_avg_sr.vhd
add_fileset_file i_acl_pipeline_keep_going9_avg_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going9_avg_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going_avg_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going_avg_sr.vhd
add_fileset_file i_acl_pipeline_keep_going_avg_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going_avg_valid_fifo.vhd
add_fileset_file loop_limiter_avg0.vhd VHDL PATH ip/loop_limiter_avg0.vhd
add_fileset_file loop_limiter_avg1.vhd VHDL PATH ip/loop_limiter_avg1.vhd
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file acl_arb2.v SYSTEM_VERILOG PATH ip/acl_arb2.v
add_fileset_file acl_ic_to_avm.v SYSTEM_VERILOG PATH ip/acl_ic_to_avm.v
add_fileset_file avg_internal.v SYSTEM_VERILOG PATH avg_internal.v

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### Parameter x interface
add_interface x conduit sink
set_interface_property x associatedClock clock
set_interface_property x associatedReset reset
set_interface_assignment x hls.cosim.name {x}
add_interface_port x x data input 64

#### Parameter y interface
add_interface y conduit sink
set_interface_property y associatedClock clock
set_interface_property y associatedReset reset
set_interface_assignment y hls.cosim.name {y}
add_interface_port y y data input 64

#### Master interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
